# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - main

trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  isTagOrientedChange: $[contains(variables['Build.SourceBranch'], 'refs/tags/')]
  # buildConfiguration: ${{ if eq(variables['isTagOrientedChange'], 'True') }}:
  #                       'Release'
  #                     else: 
  #                       'Debug'
  buildConfiguration: Release
steps:
- task: DotNetCoreCLI@2 
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  condition: xor(variables['isTagOrientedChange'], 'True')
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DotNetCoreCLI@2
  displayName: 'Push Artifact - Tag-Oriented Changes'
  condition: eq(variables['isTagOrientedChange'], 'True')
  # condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e022f26b-90cf-4ad9-9058-6eef871a63a0/1e153597-5d80-41c8-a201-050585798e03'
