# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - main

trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
- task: DotNetCoreCLI@2 
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: Build-Release
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  displayName: Build-Debug
  condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/')
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Debug'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'off'
    

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DotNetCoreCLI@2
  displayName: 'Push Artifact - Tag-Oriented Changes'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'e022f26b-90cf-4ad9-9058-6eef871a63a0/79f34750-3790-4a96-bfb6-5fbf5cd86e49'
